services:
  - type: web
    name: projeto-app1
    env: python
    envVars:
      - key: PYTHON_VERSION
        value: "3.12"
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
